# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('category_name', 'sub_category')]),
        ),
    ]
