# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadsource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('experience_years', models.IntegerField(default=0)),
                ('experience_level', models.IntegerField(default=0)),
                ('industry', models.CharField(max_length=40)),
                ('salary', models.IntegerField(default=0)),
                ('product_name', models.CharField(max_length=40)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('followup_time', models.DateTimeField(auto_now=True)),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadsource.LeadSource')),
            ],
        ),
    ]
